stages:
  clean_data:
    cmd: python src/clean_data.py
    deps:
      - data/raw
      - src/clean_data.py
    outs:
      - data/processed/train_data.pkl
      - data/processed/test_data.pkl

  train_model:
    cmd: python src/train.py
    deps:
      - data/processed/train_data.pkl
      - src/train.py
    outs:
      - models/apartment_price_model.pkl

  evaluate:
    cmd: python src/evaluate.py
    deps:
      - data/processed/test_data.pkl
      - models/apartment_price_model.pkl
      - src/evaluate.py
    outs:
      - reports/metrics.json
